[package]
name = "winluks-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
crc32c = "0.6"
winluks = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "metadata"
path = "fuzz_targets/metadata.rs"
test = false
doc = false
bench = false

[[bin]]
name = "probe"
path = "fuzz_targets/probe.rs"
test = false
doc = false
bench = false

[workspace]
